<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \BlueFinch\Checkout\ViewModel\Assets $assetViewModel
 */

$assetViewModel = $block->getAssetViewModel();

$onNewCallback = $assetViewModel->getDistViewFileUrl('BlueFinch_CheckoutNewModule::js/checkout/dist/callbacks/onNewCallback.min.js');
$newComponent = $assetViewModel->getDistViewFileUrl('BlueFinch_CheckoutNewModule::js/checkout/dist/components/NewComponent/NewComponent.min.js');
$styles = $assetViewModel->getDistViewFileUrl('BlueFinch_CheckoutNewModule::js/checkout/dist/styles.css');
?>

<script>
    window.bluefinchCheckout = window.bluefinchCheckout || {};
    window.bluefinchCheckout.callbacks = window.bluefinchCheckout.callbacks || {};
    window.bluefinchCheckout.callbacks.onNewCallback = window.bluefinchCheckout.callbacks.onNewCallback || {};
    window.bluefinchCheckout.newComponent = window.bluefinchCheckout.newComponent || {};

    window.bluefinchCheckout.callbacks.onNewCallback.onNewCallbackEvent = "<?= $escaper->escapeJs($onNewCallback) ?>";
    window.bluefinchCheckout.newComponent.newComponentPath = "<?= $escaper->escapeJs($newComponent) ?>";
</script>

<link rel="stylesheet" href="<?= $escaper->escapeHtmlAttr($styles) ?>" />